### ISSUE TITLE
Suggested license documentation

### ISSUE THREAD

**Issue by goneall** [ndip007/spdx-tools-js#1]
Suggest using the MIT rather than ISC since MIT is more common for NodeJS and JavaScript open source.

I would also suggest adding a comment in each file:

`SPDX-License-Identifier: MIT`

per license best practices.

A copy of the license should also be included in the root of the project (e.g. a License.txt file).

**Comment by ndip007** [comment]
Ok

**Comment by ndip007** [comment]
Done in [this commit](https://github.com/ndip007/spdx-tools-js/commit/f9260224696cfc6064b2cc9409a0dc36cd6dc5e9).
