### ISSUE TITLE
package-lock.json

### ISSUE THREAD

**Issue by udaykor** [ndip007/spdx-tools-js#5]
@ndip007  package.json will usually present the dependencies. You can omit the package-lock.json in your next commit.

**Comment by ndip007** [comment]
ok

**Comment by ndip007** [comment]
Done in [this commit.](https://github.com/ndip007/spdx-tools-js/commit/7d9c302a7f759d6681ed4b167158ea4d504dc705)

**Comment by ndip007** [comment]
Done in [this commit.](https://github.com/ndip007/spdx-tools-js/commit/7d9c302a7f759d6681ed4b167158ea4d504dc705)
